---
name: Build

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install NuGet CLI
        run: choco install nuget.commandline -y

      - uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Verify tools
        run: |
          dotnet --version
          nuget
          msbuild -version

      - name: Restore NuGet packages
        run: nuget restore OpenBrush.sln

      - name: Build solution
        run: msbuild OpenBrush.sln /p:Configuration=Release
